allowBuilds:
  esbuild: true
  sharp: true
  tsparticles-engine: true

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - astro@7.0.6
  - '@astrojs/internal-helpers@0.10.1'
  - '@astrojs/markdown-satteri@0.3.3'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - tsparticles-engine
